import { fromJS } from 'immutable';

import * as actions from 'actions';

export default function reports(state = fromJS({
  isFetching: false,
  error: null,
  items: {
    sample1: {
      id: 'sample1',
      name: 'Sample Report 1',
      description: 'A report example',
      keywords: ['Heat', 'Heating', 'Hot'],
      startAt: '2017-01-15T00:00:00Z',
      endAt: '2017-01-22T00:00:00Z',
      chart: {
        columns: [
          ['time', '2017-01-15', '2017-01-16', '2017-01-17', '2017-01-18', '2017-01-19',
           '2017-01-20', '2017-01-21'],
          ['count', 0, 5, 6, 0, 8, 7, 1],
        ],
      },
      heat: [0.0, 0.5, 0.7, 0.0, 1.0, 0.3, 0.0],
      messages: [
        {
          body: 'Hi. Can I get some more towels?',
          accountId: '1',
          receiverId: null,
          uploadName: null,
          uploadUrl: null,
          senderId: null,
          guestId: '21',
          id: '336',
          createdAt: '2017-02-07T17:46:54.988Z',
          uploadKey: null,
          direction: 1,
        },
        {
          body: 'Hello, thank you for contacting us. Please let us know how we can serve you.',
          accountId: '1',
          receiverId: null,
          uploadName: null,
          uploadUrl: null,
          senderId: '1',
          guestId: '21',
          id: '337',
          createdAt: '2017-02-07T17:46:55.026Z',
          uploadKey: null,
          direction: 0,
        },
        {
          body: 'I want some more towels....',
          accountId: '1',
          receiverId: null,
          uploadName: null,
          uploadUrl: null,
          senderId: null,
          guestId: '21',
          id: '338',
          createdAt: '2017-02-07T17:47:21.970Z',
          uploadKey: null,
          direction: 1,
        },
        {
          body: 'Hello, thank you for contacting us. Please let us know how we can serve you.',
          accountId: '1',
          receiverId: null,
          uploadName: null,
          uploadUrl: null,
          senderId: '1',
          guestId: '21',
          id: '339',
          createdAt: '2017-02-07T17:47:21.977Z',
          uploadKey: null,
          direction: 0,
        },
        {
          body: 'Thanks for the towels.',
          accountId: '1',
          receiverId: null,
          uploadName: null,
          uploadUrl: null,
          senderId: null,
          guestId: '21',
          id: '361',
          createdAt: '2017-02-07T19:39:23.542Z',
          uploadKey: null,
          direction: 1,
        },
        {
          body: 'You are welcome!',
          accountId: '1',
          receiverId: null,
          uploadName: null,
          uploadUrl: null,
          senderId: '2',
          guestId: '21',
          id: '362',
          createdAt: '2017-02-07T19:40:01.387Z',
          uploadKey: null,
          direction: 0,
        },
        {
          body: ':-)',
          accountId: '1',
          receiverId: null,
          uploadName: null,
          uploadUrl: null,
          senderId: null,
          guestId: '21',
          id: '363',
          createdAt: '2017-02-07T19:40:56.733Z',
          uploadKey: null,
          direction: 1,
        },
        {
          body: 'Hi Mr Avery. Hope you slept well last night.  Please come down and enjoy 20% off'
              + ' your breakfast! Mention code: FreeB112.',
          accountId: '1',
          receiverId: null,
          uploadName: null,
          uploadUrl: null,
          senderId: '2',
          guestId: '21',
          id: '580',
          createdAt: '2017-03-08T12:49:54.674Z',
          uploadKey: null,
          direction: 0,
        },
        {
          body: 'Fantasti. We will come now now!',
          accountId: '1',
          receiverId: null,
          uploadName: null,
          uploadUrl: null,
          senderId: null,
          guestId: '21',
          id: '581',
          createdAt: '2017-03-08T12:51:06.967Z',
          uploadKey: null,
          direction: 1,
        },
        {
          body: 'How did you like our breakfast?',
          accountId: '1',
          receiverId: null,
          uploadName: null,
          uploadUrl: null,
          senderId: '2',
          guestId: '21',
          id: '611',
          createdAt: '2017-03-16T16:28:31.621Z',
          uploadKey: null,
          direction: 0,
        },
        {
          body: 'HI, Johnny! Welcome to our hotel.',
          accountId: '1',
          receiverId: null,
          uploadName: null,
          uploadUrl: null,
          senderId: '2',
          guestId: '21',
          id: '623',
          createdAt: '2017-03-27T11:26:06.970Z',
          uploadKey: null,
          direction: 0,
        },
        {
          body: 'Looking forward to my stay. By the way, can I have a bottle'
              + ' of red wine when I arrive?',
          accountId: '1',
          receiverId: null,
          uploadName: null,
          uploadUrl: null,
          senderId: null,
          guestId: '21',
          id: '624',
          createdAt: '2017-03-27T11:26:47.877Z',
          uploadKey: null,
          direction: 1,
        },
      ],
    },
    sample2: {
      isDisabled: true,
      id: 'sample2',
      name: 'Sample Report 2',
      description: 'Archived report',
      keywords: ['Sheets', 'Towels'],
      startAt: '2017-01-15T00:00:00Z',
      endAt: '2017-01-22T00:00:00Z',
      chart: {
        columns: [
          ['time', '2017-01-15'],
          ['count', 5],
        ],
      },
      heat: [0.6],
      messages: {
      },
    },
  },
}), action) {
  switch (action.type) {
    case actions.FETCH_REPORT_DATA_REQUEST:
      return state.merge({
        isFetching: true,
        error: null,
      });
    case actions.FETCH_REPORT_DATA_SUCCESS:
      return state.merge({
        isFetching: false,
        error: null,
        data: {
          type: 'pie',
          columns: action.reportData,
        },
      });
    case actions.FETCH_REPORT_DATA_FAILURE:
    default:
      return state;
  }
}
